version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181        # SASL не нужен
    networks: [kafka-net]

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181

      # слушатели
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,SASL_PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker:29092,SASL_PLAINTEXT://45.132.255.35:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # SASL только на клиентском порту
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT

      # отключаем SASL к ZooKeeper
      KAFKA_ZOOKEEPER_SASL_CLIENT: "false"

      # ACL и прочее
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: "User:kafkaadmin"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # путь к JAAS для клиентских соединений
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas.conf
    volumes:
      - ./jaas.conf:/etc/kafka/jaas.conf:ro
    networks: [kafka-net]
    restart: unless-stopped
    
networks:
  kafka-net:
    driver: bridge