version: "3.9"

services:
  # --------------------------------------------------------------------------
  # ZooKeeper — нужен Kafka для работы кластера
  # --------------------------------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks: [kafka-net]

  # --------------------------------------------------------------------------
  # Kafka-брокер с SASL/PLAIN-аутентификацией
  # --------------------------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      # связь с ZooKeeper внутри сети
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181

      # слушаем и снаружи, и внутри в SASL_PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092
      # внешний адрес брокера — подставь свой публичный IP ↓
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://45.132.255.35:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT

      # включаем ACL (можно потом детализировать)
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: "User:kafkaadmin"

      # репликация топиков =1 (стенд без кластера)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # путь к JAAS-конфигу
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas.conf
    volumes:
      - ./jaas.conf:/etc/kafka/jaas.conf:ro
    networks: [kafka-net]
    restart: unless-stopped   # автозапуск при перезагрузке

networks:
  kafka-net:
    driver: bridge